sudo: required
services: docker
language: ruby
rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.7
  - 2.3.3
  - 2.3.4
  - 2.4.0
  - 2.4.1
  - 2.5.0
before_install: gem install bundler
install: bundle
script:
  - bundle exec rspec
after_success:
  - docker build -t $REPO:$(cat Dockerfile.version) .
  - docker tag $REPO:$(cat Dockerfile.version) $REPO:latest
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="$REGISTRY_USERNAME" -p="$REGISTRY_PASSWORD" $REGISTRY;
      docker push $REPO:$(cat Dockerfile.version);
      docker push $REPO:latest;
    fi